sprint04. Homework. First try.
toxicalice/MovieQuiz-ios pull request #2
Opened 2022-11-29 16:22 UTC by toxicalice

В мой проект некорректно встраиваются шрифты. В списке custom шрифтов они не отображаются. Я их достала через attributed text, а не plain text. Из-за чего такое может быть? Шрифты установила, в проект перенесла. Несколько раз. Галочки проверила.

2022-11-29 18:31 UTC, ABashkirova requested changes
1. Нужно исправить поведение констрентов(пункт 2), так чтобы текста хорошо умещались на айфонах. 
   Например, на iPhone 14 есть проблемы. Рекомендация как с этим поступить – в пул-реквесте. 
1. Верстка должна соответствовать макетам(пункт 3): 
1. LaunchScreen 
        - отступы в круг должны быть 0
        - картинка не будет заполняет весь доступный размер, можно увидеть белые полосы в зависимости устройства. 
          Нужно исправить свойство contentMode. 
<img width="1468" alt="Снимок экрана 2022-11-29 в 19 54 57" src="https://user-images.githubusercontent.com/20269264/204615470-7a12c4cb-c182-47e1-a4b1-4656f091bb39.png">

2. Главный экран:

        - шрифты не подтягиваются действительно, предложения как поправить ниже
        - текст "1/10" содержит лишний пробел у слеша
        - цвет фона не по дизайну, должен быть YP Black
        - у постера неверные скругления при ответе, и при старте приложения нет скруглений вообще 
        - сам постер имеет не верный contentMode, что не дает ему заполнить доступное пространство 
        - главный контейнер имеет отступ от safearea 20, а по макету должен быть 0
        - на новых девайсах ограничения снизу не дают вопросу отобразиться верно: чтобы этого избежать,  нужно пойти на компромисс с макетом, уменьшив отступы по краям, например 

<img width="552" alt="Снимок экрана 2022-11-29 в 20 09 00" src="https://user-images.githubusercontent.com/20269264/204615396-99e883c8-2622-4af0-a0ac-1ddabe2b4e15.png">

3. Не все функции имеют модификатор доступа (пункт 7). Для IBAction/IBOutlet тоже стоит их расставлять.

2022-11-29 18:31 UTC, ABashkirova commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
>      </dependencies>
Почему-то сториборд не подтянул шрифты. 
Должны быть выполнены условия:
1) Добавлены в ресурсы ✅
2) файлы должны иметь target MovieQuiz ✅
3) Шрифты еще нужно установить себе на компьютер (двойной клик по файлу) - перепроверить за тобой не могу)
4) добавить в Info-plist список кастомных шрифтов ✅

5) Ну и напоследок  - в сториборде выбрать custom и YP - шрифт. 

Я все это проделала, и разница с твоим сторибордом, вот в этом месте. Можешь прямо с гитхаба применить этот код, а локально подпулить и переоткрыть Xcode. 

Напиши пожалуйста версию Xcode в этот комент. В целом, IDE иногда чудит и не без багов, iOS разработчики любят мемы про это сочинять и жаловаться :) это норма. 

```suggestion
    </dependencies>
     <customFonts key="customFonts">
        <array key="YS Display-Bold.ttf">
            <string>YSDisplay-Bold</string>
        </array>
        <array key="YS Display-Medium.ttf">
            <string>YSDisplay-Medium</string>
        </array>
    </customFonts>
```

2022-11-29 18:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        get{
перед фигурной скобкой пробел всегда, после либо тоже пробел либо с новой строки с табом вперед
```suggestion
        get {
```

2022-11-29 18:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 6
Радиус скругления рамки отличается от Figma, надо исправить
<img width="550" alt="Снимок экрана 2022-11-29 в 19 46 43" src="https://user-images.githubusercontent.com/20269264/204604666-f8399d17-085b-4e72-9b5c-86a15cf142c8.png">

2022-11-29 18:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        // сюда бы я добавила дизейбл кнопки, но мне лень
😅 а давай добавим, а коммент удалим?

2022-11-29 18:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        // сюда бы я добавила дизейбл кнопки, но мне лень
в будущем убережешь себя от дабл-вызова алерта

2022-11-29 18:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let action = UIAlertAction (title: result.buttonText, style: .default) { _ in self.currentQuestionIndex = 0
1) После ключевого слова перенос строки 
2) в будущих спринтах будете изучать память и слабые ссылки, пока предлагаю сделать так:
   1) в квадратных скобках применить "ослабление ссылки"
   2) конструкцией guard разыменовать слабую ссылку на self 
Опять же, уберегаем себя от ошибок в будущем 
```suggestion
        let action = UIAlertAction (title: result.buttonText, style: .default) { [weak self] _ in 
            guard let self = self else { return }
            self.currentQuestionIndex = 0
```

2022-11-29 18:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.present(alert, animated: true, completion: nil)
Если есть возможность, лучше self опускать :) swift стремится к лаконичным конструкциям
```suggestion
        present(alert, animated: true, completion: nil)
```

2022-11-29 18:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func checkAnswer (answer: Bool) -> Bool {
```suggestion
    private func checkAnswer(answer: Bool) -> Bool {
```

2022-11-29 18:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private var correctAnswers:Int = 0
После разделителя, перед объявлением типа - ставят пробел. Также объявление типа здесь излишне, тип может автоматически вывестись из литерала 0
```suggestion
    private var correctAnswers: Int = 0
```

2022-11-29 18:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction func NoButtonDidTap(_ sender: Any) {
в swift принято свойства и функции типов именовать в нижнем camelCase. Эту стилистическую ошибку стоит поправить

2022-11-29 18:31 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction func YesButtonDidTap(_ sender: Any) {
private

2022-11-29 18:32 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        // сюда бы я добавила дизейбл кнопки, но мне лень
<img width="546" alt="Снимок экрана 2022-11-29 в 19 59 42" src="https://user-images.githubusercontent.com/20269264/204615896-9f92dd96-fe10-4782-aeb6-a08287061ec4.png">

2022-12-01 18:00 UTC, toxicalice commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
>      </dependencies>
Все пункты выполнены 
xcode Version 13.4 (13F17a)
Попробую обновить и проверить, спасибо

2022-12-01 18:16 UTC, toxicalice commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        // сюда бы я добавила дизейбл кнопки, но мне лень
okey

2022-12-01 18:27 UTC, toxicalice commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.present(alert, animated: true, completion: nil)
<img width="738" alt="Снимок экрана 2022-12-01 в 22 24 35" src="https://user-images.githubusercontent.com/117101909/205131339-ca4aa1d2-117a-4bcb-8878-57cad63a16d7.png">

Понял принял. Сверялась с вашим примером, наверное стоит поправить

2022-12-01 18:29 UTC, toxicalice commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private var correctAnswers:Int = 0
Я так меньше путаюсь, указывая тип)

2022-12-01 18:32 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.present(alert, animated: true, completion: nil)
Это тоже корректно, просто это разные стили. Но рекомендую стремиться к минимализму, но соблюдая баланс

2022-12-01 19:04 UTC, ABashkirova commented
Поменяла у верхних лейблов атрибьютед на кастом и шрифты применились, сравни: 
<img width="300" alt="Снимок экрана 2022-12-01 в 21 03 20" src="https://user-images.githubusercontent.com/20269264/205138061-840048bf-ae68-4106-8bd7-f1b3e930d4f0.png"><img width="300" alt="Снимок экрана 2022-12-01 в 21 03 27" src="https://user-images.githubusercontent.com/20269264/205138034-39556a70-10bd-4e3e-9ba8-56cb4bc5ff1a.png">

2022-12-01 19:06 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction private func YesButtonDidTap(_ sender: Any) {
к camelCase привести еще бы, обе функции. Так принято
```suggestion
    @IBAction private func yesButtonDidTap(_ sender: Any) {
```

2022-12-01 19:07 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        yesButton.isEnabled = false
класс

2022-12-01 19:24 UTC, toxicalice commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction private func YesButtonDidTap(_ sender: Any) {
Я поняла, но боюсь, что xcode сломается. Обещаю придерживаться camelCase)

2022-12-01 19:28 UTC, toxicalice commented
<img width="864" alt="Снимок экрана 2022-12-01 в 23 25 58" src="https://user-images.githubusercontent.com/117101909/205141924-27efc073-3a87-4fa5-b586-a3879825112a.png">
<img width="262" alt="Снимок экрана 2022-12-01 в 23 26 26" src="https://user-images.githubusercontent.com/117101909/205141989-d00d79a1-e028-4cd8-9c0e-3bb6d27c7d7f.png">

Я могу задать шрифт только через attributed
По прежнему в списке custom шрифтов нужного нет. Могу скринкаст записать если надо)

2022-12-02 04:55 UTC, ABashkirova commented
Вот жеж редкий кейс :)

2022-12-02 04:55 UTC, ABashkirova commented
попробуй обновиться между задачами до 14.1

2022-12-02 04:57 UTC, ABashkirova commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> +                                                            <color key="NSColor" name="textColor" catalog="System" colorSpace="catalog"/>
Это изменение надо отменить
<img width="552" alt="Снимок экрана 2022-12-02 в 06 56 30" src="https://user-images.githubusercontent.com/20269264/205217898-1f18e89e-c5e1-4c28-9edd-e3f29647e2ed.png">

2022-12-10 12:58 UTC, merged